<?php

namespace App\Clues;

use Illuminate\Database\Eloquent\Model;

class EliteTreasureTrails extends Model
{
    protected $table = 'elite_treasure_trails';

    protected $fillable = [
        'obtained',
        'kill_count',
        '3rd_age_longsword',
        '3rd_age_wand',
        '3rd_age_cloak',
        '3rd_age_bow',
        '3rd_age_range_coif',
        '3rd_age_range_top',
        '3rd_age_range_legs',
        '3rd_age_vambraces',
        '3rd_age_robe_top',
        '3rd_age_robe',
        '3rd_age_mage_hat',
        '3rd_age_amulet',
        '3rd_age_plateskirt',
        '3rd_age_platelegs',
        '3rd_age_platebody',
        '3rd_age_full_helmet',
        '3rd_age_kiteshield',
        'ring_of_3rd_age',
        'gilded_scimitar',
        'gilded_boots',
        'gilded_platebody',
        'gilded_platelegs',
        'gilded_plateskirt',
        'gilded_full_helm',
        'gilded_kiteshield',
        'gilded_med_helm',
        'gilded_chainbody',
        'gilded_sq_shield',
        'gilded_2h_sword',
        'gilded_spear',
        'gilded_hasta',
        'gilded_coif',
        'gilded_dhide_vambraces',
        'gilded_dhide_body',
        'gilded_dhide_chaps',
        'gilded_pickaxe',
        'gilded_axe',
        'gilded_spade',
        'fury_ornament_kit',
        'dragon_chainbody_ornament_kit',
        'dragon_legs/skirt_ornament_kit',
        'dragon_sq_shield_ornament_kit',
        'dragon_full_helm_ornament_kit',
        'dragon_scimitar_ornament_kit',
        'light_infinity_colour_kit',
        'dark_infinity_colour_kit',
        'holy_wraps',
        'ranger_gloves',
        'rangers_tunic',
        'rangers_tights',
        'black_dhide_body_(g)',
        'black_dhide_chaps_(g)',
        'black_dhide_body_(t)',
        'black_dhide_chaps_(t)',
        'royal_crown',
        'royal_sceptre',
        'royal_gown_top',
        'royal_gown_bottom',
        'musketeer_hat',
        'musketeer_tabard',
        'musketeer_pants',
        'dark_tuxedo_jacket',
        'dark_trousers',
        'dark_tuxedo_shoes',
        'dark_tuxedo_cuffs',
        'dark_bow_tie',
        'light_tuxedo_jacket',
        'light_trousers',
        'light_tuxedo_shoes',
        'light_tuxedo_cuffs',
        'light_bow_tie',
        'arceuus_scarf',
        'hosidius_scarf',
        'piscarilius_scarf',
        'shayzien_scarf',
        'lovakengj_scarf',
        'bronze_dragon_mask',
        'iron_dragon_mask',
        'steel_dragon_mask',
        'mithril_dragon_mask',
        'adamant_dragon_mask',
        'rune_dragon_mask',
        'lava_dragon_mask',
        'ring_of_nature',
        'katana',
        'dragon_cane',
        'briefcase',
        'bucket_helm',
        'blacksmiths_helm',
        'deerstalker',
        'afro',
        'big_pirate_hat',
        'top_hat',
        'monocle',
        'sagacious_spectacles',
        'fremennik_kilt',
        'giant_boot',
        'uris_hat',
    ];

    protected $hidden = ['user_id'];

    public function account()
    {
        return $this->belongsTo(\App\Account::class);
    }
}
