<?php

namespace App\Clues;

use Illuminate\Database\Eloquent\Model;

class MediumTreasureTrails extends Model
{
    protected $table = 'medium_treasure_trails';

    protected $fillable = [
        'obtained',
        'kill_count',
        'ranger_boots',
        'wizard_boots',
        'holy_sandals',
        'climbing_boots_(g)',
        'spiked_manacles',
        'adamant_full_helm_(t)',
        'adamant_platebody_(t)',
        'adamant_platelegs_(t)',
        'adamant_plateskirt_(t)',
        'adamant_kiteshield_(t)',
        'adamant_full_helm_(g)',
        'adamant_platebody_(g)',
        'adamant_platelegs_(g)',
        'adamant_plateskirt_(g)',
        'adamant_kiteshield_(g)',
        'adamant_shield_(h1)',
        'adamant_shield_(h2)',
        'adamant_shield_(h3)',
        'adamant_shield_(h4)',
        'adamant_shield_(h5)',
        'adamant_helm_(h1)',
        'adamant_helm_(h2)',
        'adamant_helm_(h3)',
        'adamant_helm_(h4)',
        'adamant_helm_(h5)',
        'adamant_platebody_(h1)',
        'adamant_platebody_(h2)',
        'adamant_platebody_(h3)',
        'adamant_platebody_(h4)',
        'adamant_platebody_(h5)',
        'mithril_full_helm_(g)',
        'mithril_platebody_(g)',
        'mithril_platelegs_(g)',
        'mithril_plateskirt_(g)',
        'mithril_kiteshield_(g)',
        'mithril_full_helm_(t)',
        'mithril_platebody_(t)',
        'mithril_platelegs_(t)',
        'mithril_plateskirt_(t)',
        'mithril_kiteshield_(t)',
        'green_dhide_body_(g)',
        'green_dhide_body_(t)',
        'green_dhide_chaps_(g)',
        'green_dhide_chaps_(t)',
        'saradomin_mitre',
        'saradomin_cloak',
        'guthix_mitre',
        'guthix_cloak',
        'zamorak_mitre',
        'zamorak_cloak',
        'ancient_mitre',
        'ancient_cloak',
        'ancient_stole',
        'ancient_crozier',
        'armadyl_mitre',
        'armadyl_cloak',
        'armadyl_stole',
        'armadyl_crozier',
        'bandos_mitre',
        'bandos_cloak',
        'bandos_stole',
        'bandos_crozier',
        'red_boater',
        'green_boater',
        'orange_boater',
        'black_boater',
        'blue_boater',
        'pink_boater',
        'purple_boater',
        'white_boater',
        'red_headband',
        'black_headband',
        'brown_headband',
        'white_headband',
        'blue_headband',
        'gold_headband',
        'pink_headband',
        'green_headband',
        'crier_hat',
        'crier_coat',
        'crier_bell',
        'adamant_cane',
        'arceuus_banner',
        'piscarilius_banner',
        'hosidius_banner',
        'shayzien_banner',
        'lovakengj_banner',
        'cabbage_round_shield',
        'black_unicorn_mask',
        'white_unicorn_mask',
        'cat_mask',
        'penguin_mask',
        'leprechaun_hat',
        'black_leprechaun_hat',
        'wolf_mask',
        'wolf_cloak',
        'purple_elegant_shirt',
        'purple_elegant_blouse',
        'purple_elegant_legs',
        'purple_elegant_skirt',
        'black_elegant_shirt',
        'white_elegant_blouse',
        'black_elegant_legs',
        'white_elegant_skirt',
        'pink_elegant_shirt',
        'pink_elegant_blouse',
        'pink_elegant_legs',
        'pink_elegant_skirt',
        'gold_elegant_shirt',
        'gold_elegant_blouse',
        'gold_elegant_legs',
        'gold_elegant_skirt',
        'gnomish_firelighter',
        'strength_amulet_(t)',
        'yew_comp_bow',
    ];

    protected $hidden = ['user_id'];

    public function account()
    {
        return $this->belongsTo(\App\Account::class);
    }
}
