<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTasksTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tasks', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('task');
            $table->enum('difficulty', ['easy', 'medium', 'hard', 'elite']);
            $table->integer('icon')->nullable();
            $table->string('reward')->nullable();
        });

        DB::table('tasks')->insert(
            [
                ["task" => "Get bolt racks from Barrows", "difficulty" => "easy", "icon" => "4740"],
                ["task" => "Get a Mole claw + skin", "difficulty" => "easy", "icon" => "7416"],
                ["task" => "Get 1 Ancient shard", "difficulty" => "easy", "icon" => "19677"],
                ["task" => "Get a Burnt page", "difficulty" => "easy", "icon" => "20718"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "easy", "icon" => "20708"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "easy", "icon" => "20708"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "easy", "icon" => "20708"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "easy", "icon" => "20708"],
                ["task" => "Get 5 new uniques from beginner clues", "difficulty" => "easy", "icon" => "23182"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "easy", "icon" => "2677"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "easy", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "easy", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "easy", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "easy", "icon" => "2801"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "easy", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "easy", "icon" => "2722"],
                ["task" => "Get Runner boots", "difficulty" => "easy", "icon" => "10552"],
                ["task" => "Get Penance gloves", "difficulty" => "easy", "icon" => "10553"],
                ["task" => "Get a Granite body", "difficulty" => "easy", "icon" => "10564"],
                ["task" => "Get 1 new halo", "difficulty" => "easy", "icon" => "12639"],
                ["task" => "Get the full Red decorative set", "difficulty" => "easy", "icon" => "4069"],
                ["task" => "Get the Zamorak hood & cloak", "difficulty" => "easy", "icon" => "4515"],
                ["task" => "Get the Saradomin hood & cloak", "difficulty" => "easy", "icon" => "4513"],
                ["task" => "Get 1 Angler piece", "difficulty" => "easy", "icon" => "13258"],
                ["task" => "Get 1 new unique from Gnome Restaurant", "difficulty" => "easy", "icon" => "9470"],
                ["task" => "Get a Beginner wand", "difficulty" => "easy", "icon" => "6908"],
                ["task" => "Unlock bones to peaches", "difficulty" => "easy", "icon" => "6926"],
                ["task" => "Get Infinity boots", "difficulty" => "easy", "icon" => "6920"],
                ["task" => "Get Infinity gloves", "difficulty" => "easy", "icon" => "6922"],
                ["task" => "Get a Void Knight seal", "difficulty" => "easy", "icon" => "11666"],
                ["task" => "Get Void Knight gloves", "difficulty" => "easy", "icon" => "8842"],
                ["task" => "Get a Void Knight mace", "difficulty" => "easy", "icon" => "8841"],
                ["task" => "Get 1 piece of Rogue equipment", "difficulty" => "easy", "icon" => "5554"],
                ["task" => "Get 1 piece of Rogue equipment", "difficulty" => "easy", "icon" => "5554"],
                ["task" => "Get a Fine cloth", "difficulty" => "easy", "icon" => "3470"],
                ["task" => "Get 1 piece of Lumberjack equipment", "difficulty" => "easy", "icon" => "10941"],
                ["task" => "Get the Gricoller's can", "difficulty" => "easy", "icon" => "13353"],
                ["task" => "Get 1 piece of Farmer's equipment", "difficulty" => "easy", "icon" => "13646"],
                ["task" => "Get Blue Rum", "difficulty" => "easy", "icon" => "8941"],
                ["task" => "Get Red Rum", "difficulty" => "easy", "icon" => "8940"],
                ["task" => "Get The stuff", "difficulty" => "easy", "icon" => "8988"],
                ["task" => "Get the Pearl fishing rod", "difficulty" => "easy", "icon" => "22846"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "easy", "icon" => "6798"],
                ["task" => "Get the Marksman headpiece", "difficulty" => "easy", "icon" => "2983"],
                ["task" => "Get a Tea flask", "difficulty" => "easy", "icon" => "10859"],
                ["task" => "Get a Rune satchel", "difficulty" => "easy", "icon" => "10882"],
                ["task" => "Get a Green satchel", "difficulty" => "easy", "icon" => "10878"],
                ["task" => "Get a Red satchel", "difficulty" => "easy", "icon" => "10879"],
                ["task" => "Get a Black satchel", "difficulty" => "easy", "icon" => "10880"],
                ["task" => "Get a Rune defender", "difficulty" => "easy", "icon" => "8850"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "easy", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "easy", "icon" => "21662"],
                ["task" => "Get 1 piece of Prospector equipment", "difficulty" => "easy", "icon" => "12013"],
                ["task" => "Get 1 piece of Prospector equipment", "difficulty" => "easy", "icon" => "12013"],
                ["task" => "Get 1 piece of Prospector equipment", "difficulty" => "easy", "icon" => "12013"],
                ["task" => "Get 1 piece of Prospector equipment", "difficulty" => "easy", "icon" => "12013"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "easy", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "easy", "icon" => "11341"],
                ["task" => "Get Revenant ether", "difficulty" => "easy", "icon" => "21820"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "easy", "icon" => "11850"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "easy", "icon" => "11850"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "easy", "icon" => "11850"],
                ["task" => "Get a Crawling hand", "difficulty" => "easy", "icon" => "7975"],
                ["task" => "Get a Cockatrice head", "difficulty" => "easy", "icon" => "7976"],
                ["task" => "Get 1 unique from Mogres", "difficulty" => "easy", "icon" => "6665"],
                ["task" => "Get 1 unique from Mogres", "difficulty" => "easy", "icon" => "6665"],
                ["task" => "Get a Brine sabre", "difficulty" => "easy", "icon" => "11037"],
                ["task" => "Get a Leaf-bladed sword", "difficulty" => "easy", "icon" => "11902"],
                ["task" => "Get a Black mask", "difficulty" => "easy", "icon" => "8901"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "easy", "icon" => "4119"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "easy", "icon" => "4119"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "easy", "icon" => "4119"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "easy", "icon" => "4119"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "easy", "icon" => "4119"],
                ["task" => "Get a Mystic hat (light)", "difficulty" => "easy", "icon" => "4109"],
                ["task" => "Get a Mystic robe bottom (light)", "difficulty" => "easy", "icon" => "4113"],
                ["task" => "Get Mystic gloves (light)", "difficulty" => "easy", "icon" => "4115"],
                ["task" => "Get Mystic boots (light)", "difficulty" => "easy", "icon" => "4117"],
                ["task" => "Get a Mystic hat (dark)", "difficulty" => "easy", "icon" => "4099"],
                ["task" => "Get Mystic gloves (dark)", "difficulty" => "easy", "icon" => "4105"],
                ["task" => "Get Mystic boots (dark)", "difficulty" => "easy", "icon" => "4107"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "easy", "icon" => "6568"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "easy", "icon" => "6568"],
                ["task" => "Get a Big swordfish", "difficulty" => "easy", "icon" => "7991"],
                ["task" => "Get a Big bass", "difficulty" => "easy", "icon" => "7989"],
                ["task" => "Get a Long bone", "difficulty" => "easy", "icon" => "10976"],
                ["task" => "Get an Ecumenical key", "difficulty" => "easy", "icon" => "11942"],
                ["task" => "Get 1 unique Dark totem piece", "difficulty" => "easy", "icon" => "19679"],
                ["task" => "Get Mining gloves", "difficulty" => "easy", "icon" => "21343"],
                ["task" => "Get a Right skull half", "difficulty" => "easy", "icon" => "9007"],
                ["task" => "Get a Left skull half", "difficulty" => "easy", "icon" => "9008"],
                ["task" => "Get a Top of sceptre", "difficulty" => "easy", "icon" => "9010"],
                ["task" => "Get a Bottom of sceptre", "difficulty" => "easy", "icon" => "9011"],
                ["task" => "Get a Mossy key", "difficulty" => "easy", "icon" => "22374"],
                ["task" => "Get a Giant key", "difficulty" => "easy", "icon" => "20754"],
                ["task" => "Get a Fresh crab claw & Fresh crab shell", "difficulty" => "easy", "icon" => "7536"],
                ["task" => "Get a Xeric's talisman (inert)", "difficulty" => "easy", "icon" => "13392"],
                ["task" => "Complete the Ardougne Easy Diary", "difficulty" => "easy", "icon" => "13121"],
                ["task" => "Complete the Desert Easy Diary", "difficulty" => "easy", "icon" => "13133"],
                ["task" => "Complete the Falador Easy Diary", "difficulty" => "easy", "icon" => "13117"],
                ["task" => "Complete the Fremennik Easy Diary", "difficulty" => "easy", "icon" => "13129"],
                ["task" => "Complete the Kandarin Easy Diary", "difficulty" => "easy", "icon" => "13137"],
                ["task" => "Complete the Karamja Easy Diary", "difficulty" => "easy", "icon" => "11136"],
                ["task" => "Complete the Kourend&Kebos Easy Diary", "difficulty" => "easy", "icon" => "22941"],
                ["task" => "Complete the Lumbridge&Draynor Easy Diary", "difficulty" => "easy", "icon" => "13125"],
                ["task" => "Complete the Morytania Easy Diary", "difficulty" => "easy", "icon" => "13112"],
                ["task" => "Complete the Varrock Easy Diary", "difficulty" => "easy", "icon" => "13104"],
                ["task" => "Complete the Western Provinces Easy Diary", "difficulty" => "easy", "icon" => "13141"],
                ["task" => "Complete the Wilderness Easy Diary", "difficulty" => "easy", "icon" => "13108"],

                ["task" => "Get 1 unique from Barrows", "difficulty" => "medium", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "medium", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "medium", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "medium", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "medium", "icon" => "4708"],
                ["task" => "Get Bryophyta's essence", "difficulty" => "medium", "icon" => "22372"],
                ["task" => "Get 1 unique from Crazy Archeologist", "difficulty" => "medium", "icon" => "11990"],
                ["task" => "Get 1 unique from Crazy Archeologist", "difficulty" => "medium", "icon" => "11990"],
                ["task" => "Get 1 unique from Crazy Archeologist", "difficulty" => "medium", "icon" => "11990"],
                ["task" => "Get a Fire cape", "difficulty" => "medium", "icon" => "6570"],
                ["task" => "Get Granite dust", "difficulty" => "medium", "icon" => "21726"],
                ["task" => "Get a Hill giant club", "difficulty" => "medium", "icon" => "20756"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "medium", "icon" => "20708"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "medium", "icon" => "20708"],
                ["task" => "Get 1 Unique from Wintertodt", "difficulty" => "medium", "icon" => "20708"],
                ["task" => "Get Zulrah's scales", "difficulty" => "medium", "icon" => "12934"],
                ["task" => "Get a Zul-andra teleport", "difficulty" => "medium", "icon" => "12938"],
                ["task" => "Get a Dark relic or Torn prayer scroll", "difficulty" => "medium", "icon" => "21027"],
                ["task" => "Get a Dark relic or Torn prayer scroll", "difficulty" => "medium", "icon" => "21027"],
                ["task" => "Get 5 new uniques from beginner clues", "difficulty" => "medium", "icon" => "23182"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "medium", "icon" => "2677"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "medium", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "medium", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "medium", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "medium", "icon" => "2801"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "medium", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "medium", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "medium", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "medium", "icon" => "2722"],
                ["task" => "Get a Fighter hat", "difficulty" => "medium", "icon" => "10548"],
                ["task" => "Get a Healer hat", "difficulty" => "medium", "icon" => "10547"],
                ["task" => "Get a Runner hat", "difficulty" => "medium", "icon" => "10549"],
                ["task" => "Get a Ranger hat", "difficulty" => "medium", "icon" => "10550"],
                ["task" => "Get a Fighter torso", "difficulty" => "medium", "icon" => "10551"],
                ["task" => "Get a Granite helm", "difficulty" => "medium", "icon" => "10589"],
                ["task" => "Get 1 new halo", "difficulty" => "medium", "icon" => "12639"],
                ["task" => "Get the Decorative ranged set", "difficulty" => "medium", "icon" => "11899"],
                ["task" => "Get the Decorative magic set", "difficulty" => "medium", "icon" => "11896"],
                ["task" => "Get 1 Angler piece", "difficulty" => "medium", "icon" => "13258"],
                ["task" => "Get 1 Angler piece", "difficulty" => "medium", "icon" => "13258"],
                ["task" => "Get 1 Angler piece", "difficulty" => "medium", "icon" => "13258"],
                ["task" => "Get 1 new unique from Gnome Restaurant", "difficulty" => "medium", "icon" => "9470"],
                ["task" => "Get 1 new unique from Gnome Restaurant", "difficulty" => "medium", "icon" => "9470"],
                ["task" => "Upgrade the MTA wand once", "difficulty" => "medium", "icon" => "6910"],
                ["task" => "Upgrade the MTA wand once", "difficulty" => "medium", "icon" => "6910"],
                ["task" => "Upgrade the MTA wand once", "difficulty" => "medium", "icon" => "6910"],
                ["task" => "Get an Infinity hat", "difficulty" => "medium", "icon" => "6918"],
                ["task" => "Get a Mage's book", "difficulty" => "medium", "icon" => "6889"],
                ["task" => "Get a Void melee helm", "difficulty" => "medium", "icon" => "11665"],
                ["task" => "Get a Void mage helm", "difficulty" => "medium", "icon" => "11663"],
                ["task" => "Get a Void ranger helm", "difficulty" => "medium", "icon" => "11664"],
                ["task" => "Get a Void Knight top", "difficulty" => "medium", "icon" => "8839"],
                ["task" => "Get a Void Knight robe", "difficulty" => "medium", "icon" => "8840"],
                ["task" => "Get 1 piece of Rogue equipment", "difficulty" => "medium", "icon" => "5554"],
                ["task" => "Get 1 piece of Rogue equipment", "difficulty" => "medium", "icon" => "5554"],
                ["task" => "Get 1 piece of Rogue equipment", "difficulty" => "medium", "icon" => "5554"],
                ["task" => "Get an Amulet of the damned", "difficulty" => "medium", "icon" => "12851"],
                ["task" => "Get a Flamtaer bag", "difficulty" => "medium", "icon" => "12854"],
                ["task" => "Get 1 piece of Lumberjack equipment", "difficulty" => "medium", "icon" => "10941"],
                ["task" => "Get 1 piece of Lumberjack equipment", "difficulty" => "medium", "icon" => "10941"],
                ["task" => "Get 1 piece of Lumberjack equipment", "difficulty" => "medium", "icon" => "10941"],
                ["task" => "Get 1 piece of Farmer's equipment", "difficulty" => "medium", "icon" => "13646"],
                ["task" => "Get 1 piece of Farmer's equipment", "difficulty" => "medium", "icon" => "13646"],
                ["task" => "Get 1 piece of Farmer's equipment", "difficulty" => "medium", "icon" => "13646"],
                ["task" => "Get the Seed box", "difficulty" => "medium", "icon" => "13639"],
                ["task" => "Get 1 Naval set", "difficulty" => "medium", "icon" => "8952"],
                ["task" => "Get 1 Naval set", "difficulty" => "medium", "icon" => "8952"],
                ["task" => "Get the Cutthroat flag", "difficulty" => "medium", "icon" => "8966"],
                ["task" => "Get the Guilded smile flag", "difficulty" => "medium", "icon" => "8967"],
                ["task" => "Get the Pearl fly fishing rod", "difficulty" => "medium", "icon" => "22844"],
                ["task" => "Get the Pearl barbarian rod", "difficulty" => "medium", "icon" => "22842"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "medium", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "medium", "icon" => "6798"],
                ["task" => "Get 1 unique Elder chaos robe piece", "difficulty" => "medium", "icon" => "20595"],
                ["task" => "Get 1 unique Elder chaos robe piece", "difficulty" => "medium", "icon" => "20595"],
                ["task" => "Get the Bowmaster headpiece", "difficulty" => "medium", "icon" => "2988"],
                ["task" => "Get a Gold satchel", "difficulty" => "medium", "icon" => "10881"],
                ["task" => "Get a Plain satchel", "difficulty" => "medium", "icon" => "10877"],
                ["task" => "Get a Dragon defender", "difficulty" => "medium", "icon" => "12954"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "medium", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "medium", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "medium", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "medium", "icon" => "21662"],
                ["task" => "Get the Coal bag", "difficulty" => "medium", "icon" => "764"],
                ["task" => "Get the Gem bag", "difficulty" => "medium", "icon" => "766"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "medium", "icon" => "11341"],
                ["task" => "Get a Revenant cave teleport", "difficulty" => "medium", "icon" => "21802"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "medium", "icon" => "11850"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "medium", "icon" => "11850"],
                ["task" => "Get 1 piece of Graceful equipment", "difficulty" => "medium", "icon" => "11850"],
                ["task" => "Get tier 5 Shayzien armour", "difficulty" => "medium", "icon" => "13379"],
                ["task" => "Get a Basilisk head", "difficulty" => "medium", "icon" => "7977"],
                ["task" => "Get a Granite maul", "difficulty" => "medium", "icon" => "4153"],
                ["task" => "Get a Leaf-bladed battleaxe", "difficulty" => "medium", "icon" => "20727"],
                ["task" => "Get a Granite longsword", "difficulty" => "medium", "icon" => "21646"],
                ["task" => "Get Granite legs", "difficulty" => "medium", "icon" => "6809"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "medium", "icon" => "4121"],
                ["task" => "Get the next tier of metal boots", "difficulty" => "medium", "icon" => "4121"],
                ["task" => "Get a Mystic robe top (light)", "difficulty" => "medium", "icon" => "4111"],
                ["task" => "Get a Mystic robe top (dark)", "difficulty" => "medium", "icon" => "4101"],
                ["task" => "Get a Mystic robe bottom (dark)", "difficulty" => "medium", "icon" => "4103"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "medium", "icon" => "6568"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "medium", "icon" => "6568"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "medium", "icon" => "6568"],
                ["task" => "Get 1 unique Tzhaar drop", "difficulty" => "medium", "icon" => "6568"],
                ["task" => "Get a Big shark", "difficulty" => "medium", "icon" => "7993"],
                ["task" => "Get a Curved bone", "difficulty" => "medium", "icon" => "10977"],
                ["task" => "Get 1 unique Dark totem piece", "difficulty" => "medium", "icon" => "19679"],
                ["task" => "Get 1 unique Dark totem piece", "difficulty" => "medium", "icon" => "19679"],
                ["task" => "Get a Shaman mask", "difficulty" => "medium", "icon" => "21838"],
                ["task" => "Get Superior mining gloves", "difficulty" => "medium", "icon" => "21345"],
                ["task" => "Get a Bracelet of ethereum", "difficulty" => "medium", "icon" => "21816"],
                ["task" => "Complete the Ardougne Medium Diary", "difficulty" => "medium", "icon" => "13122"],
                ["task" => "Complete the Desert Medium Diary", "difficulty" => "medium", "icon" => "13134"],
                ["task" => "Complete the Falador Medium Diary", "difficulty" => "medium", "icon" => "13118"],
                ["task" => "Complete the Fremennik Medium Diary", "difficulty" => "medium", "icon" => "13130"],
                ["task" => "Complete the Kandarin Medium Diary", "difficulty" => "medium", "icon" => "13138"],
                ["task" => "Complete the Karamja Medium Diary", "difficulty" => "medium", "icon" => "11138"],
                ["task" => "Complete the Kourend&Kebos Medium Diary", "difficulty" => "medium", "icon" => "22943"],
                ["task" => "Complete the Lumbridge&Draynor Medium Diary", "difficulty" => "medium", "icon" => "13126"],
                ["task" => "Complete the Morytania Medium Diary", "difficulty" => "medium", "icon" => "13113"],
                ["task" => "Complete the Varrock Medium Diary", "difficulty" => "medium", "icon" => "13105"],
                ["task" => "Complete the Western Provinces Medium Diary", "difficulty" => "medium", "icon" => "13142"],
                ["task" => "Complete the Wilderness Medium Diary", "difficulty" => "medium", "icon" => "13109"],

                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get a unique from Unsired", "difficulty" => "hard", "icon" => "4708"],
                ["task" => "Get an Abyssal whip", "difficulty" => "hard", "icon" => "4151"],
                ["task" => "Get a unique Dragon item from Mount Karuulm", "difficulty" => "hard", "icon" => "1149"],
                ["task" => "Get a unique Dragon item from Mount Karuulm", "difficulty" => "hard", "icon" => "1149"],
                ["task" => "Get a unique Dragon item from Mount Karuulm", "difficulty" => "hard", "icon" => "1149"],
                ["task" => "Get a unique Dragon item from Mount Karuulm", "difficulty" => "hard", "icon" => "1149"],
                ["task" => "Get a Dragon pickaxe", "difficulty" => "hard", "icon" => "11920"],
                ["task" => "Get a Dragon 2h sword", "difficulty" => "hard", "icon" => "7158"],
                ["task" => "Get 1 unique crystal/stone from Cerberus", "difficulty" => "hard", "icon" => "13231"],
                ["task" => "Get 1 Key master teleport", "difficulty" => "hard", "icon" => "13249"],
                ["task" => "Get a unique shard 1", "difficulty" => "hard", "icon" => "11928"],
                ["task" => "Get a unique shard 1", "difficulty" => "hard", "icon" => "11928"],
                ["task" => "Get the Pet chaos elemental", "difficulty" => "hard", "icon" => "11995"],
                ["task" => "Get 1 unique Godsword shard", "difficulty" => "hard", "icon" => "11818"],
                ["task" => "Get 1 unique drop from Commander Zilyana", "difficulty" => "hard", "icon" => "11838"],
                ["task" => "Get a unique ring from Rex", "difficulty" => "hard", "icon" => "6737"],
                ["task" => "Get a unique ring from Rex", "difficulty" => "hard", "icon" => "6737"],
                ["task" => "Get a unique ring/seercull from Supreme", "difficulty" => "hard", "icon" => "6733"],
                ["task" => "Get a unique ring/mud staff from Prime", "difficulty" => "hard", "icon" => "6731"],
                ["task" => "Get a unique ring/seercull from Supreme", "difficulty" => "hard", "icon" => "6733"],
                ["task" => "Get a unique ring/mud staff from Prime", "difficulty" => "hard", "icon" => "6731"],
                ["task" => "Get a Dragon axe", "difficulty" => "hard", "icon" => "6739"],
                ["task" => "Get 1 unique drop from Grotesque Gardians", "difficulty" => "hard", "icon" => "21748"],
                ["task" => "Get 1 unique drop from Grotesque Gardians", "difficulty" => "hard", "icon" => "21748"],
                ["task" => "Get 1 unique drop from Grotesque Gardians", "difficulty" => "hard", "icon" => "21748"],
                ["task" => "Get 1 unique drop from Grotesque Gardians", "difficulty" => "hard", "icon" => "21748"],
                ["task" => "Get a Kq head", "difficulty" => "hard", "icon" => "7981"],
                ["task" => "Get a Dragon chainbody", "difficulty" => "hard", "icon" => "2513"],
                ["task" => "Get Kbd heads", "difficulty" => "hard", "icon" => "7980"],
                ["task" => "Get 1 unique drop from Kraken", "difficulty" => "hard", "icon" => "12655"],
                ["task" => "Get 1 unique drop from Kraken", "difficulty" => "hard", "icon" => "12655"],
                ["task" => "Get a unique shard 3", "difficulty" => "hard", "icon" => "11930"],
                ["task" => "Get a unique shard 3", "difficulty" => "hard", "icon" => "11930"],
                ["task" => "Get Vorkath's head", "difficulty" => "hard", "icon" => "2425"],
                ["task" => "Get 1 unique from Zulrah", "difficulty" => "hard", "icon" => "12921"],
                ["task" => "Get 1 unique from Zulrah", "difficulty" => "hard", "icon" => "12921"],
                ["task" => "Get 1 unique from Zulrah", "difficulty" => "hard", "icon" => "12921"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "hard", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "hard", "icon" => "20997"],
                ["task" => "Get a Vial of blood", "difficulty" => "hard", "icon" => "22405"],
                ["task" => "Get 5 new uniques from beginner clues", "difficulty" => "hard", "icon" => "23182"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "hard", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "hard", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "hard", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "hard", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "hard", "icon" => "2677"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "hard", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "hard", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "hard", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "hard", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "hard", "icon" => "2801"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "hard", "icon" => "2722"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "hard", "icon" => "12073"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "hard", "icon" => "12073"],
                ["task" => "Get a Penance skirt", "difficulty" => "hard", "icon" => "10555"],
                ["task" => "Get 1 new halo", "difficulty" => "hard", "icon" => "12639"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get 1 new unique from Gnome Restaurant", "difficulty" => "hard", "icon" => "9470"],
                ["task" => "Get an Infinity top", "difficulty" => "hard", "icon" => "6916"],
                ["task" => "Get Infinity bottoms", "difficulty" => "hard", "icon" => "20575"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get 1 White decorative piece", "difficulty" => "hard", "icon" => "4506"],
                ["task" => "Get an Elite void top", "difficulty" => "hard", "icon" => "15737"],
                ["task" => "Get an Elite void robe", "difficulty" => "hard", "icon" => "15739"],
                ["task" => "Get 1 Naval set", "difficulty" => "hard", "icon" => "8952"],
                ["task" => "Get 1 Naval set", "difficulty" => "hard", "icon" => "8952"],
                ["task" => "Get 1 Naval set", "difficulty" => "hard", "icon" => "8952"],
                ["task" => "Get the Bronze fist flag", "difficulty" => "hard", "icon" => "8968"],
                ["task" => "Get the Lucky shot flag", "difficulty" => "hard", "icon" => "8969"],
                ["task" => "Get the Fish sack", "difficulty" => "hard", "icon" => "22838"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "hard", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "hard", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "hard", "icon" => "6798"],
                ["task" => "Get 1 unique Elder chaos robe piece", "difficulty" => "hard", "icon" => "20595"],
                ["task" => "Get the Dragon archer headpiece", "difficulty" => "hard", "icon" => "2993"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "hard", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "hard", "icon" => "21662"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "hard", "icon" => "19589"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "hard", "icon" => "19529"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "hard", "icon" => "19529"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "hard", "icon" => "19529"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "hard", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "hard", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "hard", "icon" => "11341"],
                ["task" => "Get 1 unique Ancient artefact", "difficulty" => "hard", "icon" => "21807"],
                ["task" => "Get 1 unique Ancient artefact", "difficulty" => "hard", "icon" => "21807"],
                ["task" => "Get an Ancient crystal", "difficulty" => "hard", "icon" => "21804"],
                ["task" => "Get a Kurask head", "difficulty" => "hard", "icon" => "7978"],
                ["task" => "Get Granite boots", "difficulty" => "hard", "icon" => "21643"],
                ["task" => "Get Dragon boots", "difficulty" => "hard", "icon" => "11840"],
                ["task" => "Get a Dark bow", "difficulty" => "hard", "icon" => "11235"],
                ["task" => "Get 1 unique from Thermonuclear smoke devil", "difficulty" => "hard", "icon" => "12648"],
                ["task" => "Get 1 unique from Brimstone chest", "difficulty" => "hard", "icon" => "23047"],
                ["task" => "Get a unique item from Drakes", "difficulty" => "hard", "icon" => "22960"],
                ["task" => "Get a unique item from Drakes", "difficulty" => "hard", "icon" => "22960"],
                ["task" => "Get 1 unique from Brimstone chest", "difficulty" => "hard", "icon" => "23047"],
                ["task" => "Get 1 unique from Brimstone chest", "difficulty" => "hard", "icon" => "23047"],
                ["task" => "Get 1 unique Obsidian armour drop", "difficulty" => "hard", "icon" => "21298"],
                ["task" => "Get 1 unique Obsidian armour drop", "difficulty" => "hard", "icon" => "21298"],
                ["task" => "Get a Dragon warhammer", "difficulty" => "hard", "icon" => "13576"],
                ["task" => "Get a Pharaoh's sceptre", "difficulty" => "hard", "icon" => "9044"],
                ["task" => "Get Chewed bones", "difficulty" => "hard", "icon" => "11338"],
                ["task" => "Get Dragon limbs ", "difficulty" => "hard", "icon" => "21918"],
                ["task" => "Get a Dragon spear", "difficulty" => "hard", "icon" => "1249"],
                ["task" => "Get Expert mining gloves", "difficulty" => "hard", "icon" => "21392"],
                ["task" => "Complete 6 Ardougne Hard Diary tasks", "difficulty" => "hard", "icon" => "13123"],
                ["task" => "Complete 6 Ardougne Hard Diary tasks", "difficulty" => "hard", "icon" => "13123"],
                ["task" => "Complete 5 Desert Hard Diary tasks", "difficulty" => "hard", "icon" => "13135"],
                ["task" => "Complete 5 Desert Hard Diary tasks", "difficulty" => "hard", "icon" => "13135"],
                ["task" => "Complete 5 Falador Hard Diary tasks", "difficulty" => "hard", "icon" => "13119"],
                ["task" => "Complete 6 Falador Hard Diary tasks", "difficulty" => "hard", "icon" => "13119"],
                ["task" => "Complete 4 Fremennik Hard Diary tasks", "difficulty" => "hard", "icon" => "13131"],
                ["task" => "Complete 5 Fremennik Hard Diary tasks", "difficulty" => "hard", "icon" => "13131"],
                ["task" => "Complete 5 Kandarin Hard Diary tasks", "difficulty" => "hard", "icon" => "13139"],
                ["task" => "Complete 6 Kandarin Hard Diary tasks", "difficulty" => "hard", "icon" => "13139"],
                ["task" => "Complete 5 Karamja Hard Diary tasks", "difficulty" => "hard", "icon" => "11140"],
                ["task" => "Complete 5 Karamja Hard Diary tasks", "difficulty" => "hard", "icon" => "11140"],
                ["task" => "Complete 5 Kourend&Kebos Hard Diary tasks", "difficulty" => "hard", "icon" => "22945"],
                ["task" => "Complete 5 Kourend&Kebos Hard Diary tasks", "difficulty" => "hard", "icon" => "22945"],
                ["task" => "Complete 5 Lumbridge&Draynor Hard Diary tasks", "difficulty" => "hard", "icon" => "13127"],
                ["task" => "Complete 6 Lumbridge&Draynor Hard Diary tasks", "difficulty" => "hard", "icon" => "13127"],
                ["task" => "Complete 5 Morytania Hard Diary tasks", "difficulty" => "hard", "icon" => "13114"],
                ["task" => "Complete 5 Morytania Hard Diary tasks", "difficulty" => "hard", "icon" => "13114"],
                ["task" => "Complete 5 Varrock Hard Diary tasks", "difficulty" => "hard", "icon" => "13106"],
                ["task" => "Complete 5 Varrock Hard Diary tasks", "difficulty" => "hard", "icon" => "13106"],
                ["task" => "Complete 6 Western Provinces Hard Diary tasks", "difficulty" => "hard", "icon" => "13143"],
                ["task" => "Complete 7 Western Provinces Hard Diary tasks", "difficulty" => "hard", "icon" => "13143"],
                ["task" => "Complete 5 Wilderness Hard Diary tasks", "difficulty" => "hard", "icon" => "13110"],
                ["task" => "Complete 5 Wilderness Hard Diary tasks", "difficulty" => "hard", "icon" => "13110"],

                ["task" => "Get 1 unique from Barrows", "difficulty" => "elite", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "elite", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "elite", "icon" => "4708"],
                ["task" => "Get 1 unique from Barrows", "difficulty" => "elite", "icon" => "4708"],
                ["task" => "Get 1 Bludgeon piece", "difficulty" => "elite", "icon" => "13274"],
                ["task" => "Get 1 Bludgeon piece", "difficulty" => "elite", "icon" => "13274"],
                ["task" => "Get 1 Bludgeon piece", "difficulty" => "elite", "icon" => "13274"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get a Jar of miasma", "difficulty" => "elite", "icon" => "13277"],
                ["task" => "Get an Abyssal head", "difficulty" => "elite", "icon" => "7979"],
                ["task" => "Get an Abyssal dagger", "difficulty" => "elite", "icon" => "13265"],
                ["task" => "Get 1 Unique from Alchemical hydra", "difficulty" => "elite", "icon" => "22973"],
                ["task" => "Get a Tyrannical ring", "difficulty" => "elite", "icon" => "12603"],
                ["task" => "Get 1 unique crystal/stone from Cerberus", "difficulty" => "elite", "icon" => "13231"],
                ["task" => "Get 1 unique crystal/stone from Cerberus", "difficulty" => "elite", "icon" => "13231"],
                ["task" => "Get 1 unique crystal/stone from Cerberus", "difficulty" => "elite", "icon" => "13231"],
                ["task" => "Get 1 unique Godsword shard", "difficulty" => "elite", "icon" => "11818"],
                ["task" => "Get 1 unique Godsword shard", "difficulty" => "elite", "icon" => "11818"],
                ["task" => "Get 1 unique drop from Commander Zilyana", "difficulty" => "elite", "icon" => "11838"],
                ["task" => "Get 1 unique drop from Commander Zilyana", "difficulty" => "elite", "icon" => "11838"],
                ["task" => "Get 1 unique drop from Commander Zilyana", "difficulty" => "elite", "icon" => "11838"],
                ["task" => "Get 1 unique from Corporeal Beast", "difficulty" => "elite", "icon" => "12819"],
                ["task" => "Get 1 unique from Corporeal Beast", "difficulty" => "elite", "icon" => "12819"],
                ["task" => "Get 1 unique from Corporeal Beast", "difficulty" => "elite", "icon" => "12819"],
                ["task" => "Get 1 unique drop from General Graardor", "difficulty" => "elite", "icon" => "11832"],
                ["task" => "Get 1 unique drop from General Graardor", "difficulty" => "elite", "icon" => "11832"],
                ["task" => "Get 1 unique drop from General Graardor", "difficulty" => "elite", "icon" => "11832"],
                ["task" => "Get 1 unique drop from General Graardor", "difficulty" => "elite", "icon" => "11832"],
                ["task" => "Get a Draconic visage", "difficulty" => "elite", "icon" => "11286"],
                ["task" => "Get a Pet kraken", "difficulty" => "elite", "icon" => "12655"],
                ["task" => "Get 1 unique drop from Kraken", "difficulty" => "elite", "icon" => "12004"],
                ["task" => "Get 1 unique drop from Kree'arra", "difficulty" => "elite", "icon" => "11826"],
                ["task" => "Get 1 unique drop from Kree'arra", "difficulty" => "elite", "icon" => "11826"],
                ["task" => "Get 1 unique drop from Kree'arra", "difficulty" => "elite", "icon" => "11826"],
                ["task" => "Get 1 unique drop from Kree'arra", "difficulty" => "elite", "icon" => "11826"],
                ["task" => "Get 1 unique drop from K'ril Tsutsaroth", "difficulty" => "elite", "icon" => "11824"],
                ["task" => "Get 1 unique drop from K'ril Tsutsaroth", "difficulty" => "elite", "icon" => "11824"],
                ["task" => "Get 1 unique drop from K'ril Tsutsaroth", "difficulty" => "elite", "icon" => "11824"],
                ["task" => "Get 1 unique drop from K'ril Tsutsaroth", "difficulty" => "elite", "icon" => "11824"],
                ["task" => "Get Scorpia's offspring", "difficulty" => "elite", "icon" => "13181"],
                ["task" => "Get a Dark claw", "difficulty" => "elite", "icon" => "21275"],
                ["task" => "Get a full Dark totem drop from Skotizo", "difficulty" => "elite", "icon" => "19685"],
                ["task" => "Get a Pet smoke devil", "difficulty" => "elite", "icon" => "12648"],
                ["task" => "Get 1 unique from Thermonuclear smoke devil", "difficulty" => "elite", "icon" => "12002"],
                ["task" => "Get a Treasonous ring", "difficulty" => "elite", "icon" => "12605"],
                ["task" => "Get a Ring of the gods", "difficulty" => "elite", "icon" => "12601"],
                ["task" => "Get a Dragonbone necklace", "difficulty" => "elite", "icon" => "22111"],
                ["task" => "Get 1 unique from Zulrah", "difficulty" => "elite", "icon" => "12922"],
                ["task" => "Get 1 unique from Zulrah", "difficulty" => "elite", "icon" => "12922"],
                ["task" => "Get a cut Onyx from Tekton", "difficulty" => "elite", "icon" => "6573"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Chambers of Xeric", "difficulty" => "elite", "icon" => "20997"],
                ["task" => "Get 1 unique from Theatre of Blood", "difficulty" => "elite", "icon" => "22477"],
                ["task" => "Get 1 unique from Theatre of Blood", "difficulty" => "elite", "icon" => "22477"],
                ["task" => "Get 1 unique from Theatre of Blood", "difficulty" => "elite", "icon" => "22477"],
                ["task" => "Get 1 unique from Theatre of Blood", "difficulty" => "elite", "icon" => "22477"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "elite", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "elite", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "elite", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "elite", "icon" => "2677"],
                ["task" => "Get 5 new uniques from easy clues", "difficulty" => "elite", "icon" => "2677"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "elite", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "elite", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "elite", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "elite", "icon" => "2801"],
                ["task" => "Get 5 new uniques from medium clues", "difficulty" => "elite", "icon" => "2801"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from hard clues", "difficulty" => "elite", "icon" => "2722"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "elite", "icon" => "12073"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "elite", "icon" => "12073"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "elite", "icon" => "12073"],
                ["task" => "Get 5 new uniques from elite clues", "difficulty" => "elite", "icon" => "12073"],
                ["task" => "Get 5 new uniques from master clues", "difficulty" => "elite", "icon" => "19835"],
                ["task" => "Get 5 new uniques from master clues", "difficulty" => "elite", "icon" => "19835"],
                ["task" => "Get a Saradomin banner", "difficulty" => "elite", "icon" => "4037"],
                ["task" => "Get a Zamorak banner", "difficulty" => "elite", "icon" => "4039"],
                ["task" => "Get a Gold decorative helm", "difficulty" => "elite", "icon" => "4511"],
                ["task" => "Get a Gold decorative sword", "difficulty" => "elite", "icon" => "4508"],
                ["task" => "Get 1 Naval set", "difficulty" => "elite", "icon" => "8952"],
                ["task" => "Get 1 Naval set", "difficulty" => "elite", "icon" => "8952"],
                ["task" => "Get the Treasure flag", "difficulty" => "elite", "icon" => "8970"],
                ["task" => "Get the Phasmatys flag", "difficulty" => "elite", "icon" => "8970"],
                ["task" => "Get Rocky", "difficulty" => "elite", "icon" => "20663"],
                ["task" => "Get Herbi", "difficulty" => "elite", "icon" => "21509"],
                ["task" => "Get the Chompy chick", "difficulty" => "elite", "icon" => "13071"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "elite", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "elite", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "elite", "icon" => "6798"],
                ["task" => "Get 1 unique Champion scroll", "difficulty" => "elite", "icon" => "6798"],
                ["task" => "Get the Expert dragon archer headpiece", "difficulty" => "elite", "icon" => "2995"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "elite", "icon" => "21662"],
                ["task" => "Get 1 unique note from Fossil Island", "difficulty" => "elite", "icon" => "21662"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "elite", "icon" => "19529"],
                ["task" => "Get a unique from Demonic gorillas", "difficulty" => "elite", "icon" => "19529"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "elite", "icon" => "11341"],
                ["task" => "Get 2 unique Ancient pages", "difficulty" => "elite", "icon" => "11341"],
                ["task" => "Get 1 unique Ancient artefact", "difficulty" => "elite", "icon" => "21807"],
                ["task" => "Get 1 unique Ancient artefact", "difficulty" => "elite", "icon" => "21807"],
                ["task" => "Get 1 unique Ancient artefact", "difficulty" => "elite", "icon" => "21807"],
                ["task" => "Get 1 unique Revenant megarare", "difficulty" => "elite", "icon" => "22547"],
                ["task" => "Get 1 unique Revenant megarare", "difficulty" => "elite", "icon" => "22547"],
                ["task" => "Get a Dust battlestaff", "difficulty" => "elite", "icon" => "20736"],
                ["task" => "Get a Mist battlestaff", "difficulty" => "elite", "icon" => "20730"],
                ["task" => "Get 1 unique from Brimstone chest", "difficulty" => "elite", "icon" => "23047"],
                ["task" => "Get 1 unique from Brimstone chest", "difficulty" => "elite", "icon" => "23047"],
                ["task" => "Get 1 unique Obsidian armour drop", "difficulty" => "elite", "icon" => "21298"],
                ["task" => "Get a Toktz-mej-tal", "difficulty" => "elite", "icon" => "6526"],
                ["task" => "Get a Dragon metal slice", "difficulty" => "elite", "icon" => "22100"],
                ["task" => "Get a Dragon metal lump", "difficulty" => "elite", "icon" => "22103"],
                ["task" => "Get a Pirate's hook", "difficulty" => "elite", "icon" => "2997"],
                ["task" => "Complete 2 Ardougne Elite Diary tasks", "difficulty" => "elite", "icon" => "13124"],
                ["task" => "Complete 2 Ardougne Elite Diary tasks", "difficulty" => "elite", "icon" => "13124"],
                ["task" => "Complete 2 Ardougne Elite Diary tasks", "difficulty" => "elite", "icon" => "13124"],
                ["task" => "Complete 2 Ardougne Elite Diary tasks", "difficulty" => "elite", "icon" => "13124"],
                ["task" => "Complete 2 Desert Elite Diary tasks", "difficulty" => "elite", "icon" => "13136"],
                ["task" => "Complete 2 Desert Elite Diary tasks", "difficulty" => "elite", "icon" => "13136"],
                ["task" => "Complete 2 Desert Elite Diary tasks", "difficulty" => "elite", "icon" => "13136"],
                ["task" => "Complete 2 Falador Elite Diary tasks", "difficulty" => "elite", "icon" => "13120"],
                ["task" => "Complete 2 Falador Elite Diary tasks", "difficulty" => "elite", "icon" => "13120"],
                ["task" => "Complete 2 Falador Elite Diary tasks", "difficulty" => "elite", "icon" => "13120"],
                ["task" => "Complete the Fremennik Elite Diary tasks", "difficulty" => "elite", "icon" => "18670"],
                ["task" => "Complete 2 Kandarin Elite Diary tasks", "difficulty" => "elite", "icon" => "13140"],
                ["task" => "Complete 2 Kandarin Elite Diary tasks", "difficulty" => "elite", "icon" => "13140"],
                ["task" => "Complete 3 Kandarin Elite Diary tasks", "difficulty" => "elite", "icon" => "13140"],
                ["task" => "Complete 2 Karamja Elite Diary tasks", "difficulty" => "elite", "icon" => "13103"],
                ["task" => "Complete 3 Karamja Elite Diary tasks", "difficulty" => "elite", "icon" => "13103"],
                ["task" => "Complete 2 Kourend&Kebos Elite Diary tasks", "difficulty" => "elite", "icon" => "22947"],
                ["task" => "Complete 3 Kourend&Kebos Elite Diary tasks", "difficulty" => "elite", "icon" => "22947"],
                ["task" => "Complete 2 Lumbridge&Draynor Elite Diary tasks", "difficulty" => "elite", "icon" => "18666"],
                ["task" => "Complete 2 Lumbridge&Draynor Elite Diary tasks", "difficulty" => "elite", "icon" => "18666"],
                ["task" => "Complete 2 Lumbridge&Draynor Elite Diary tasks", "difficulty" => "elite", "icon" => "18666"],
                ["task" => "Complete 2 Morytania Elite Diary tasks", "difficulty" => "elite", "icon" => "13115"],
                ["task" => "Complete 3 Morytania Elite Diary tasks", "difficulty" => "elite", "icon" => "13115"],
                ["task" => "Complete 2 Varrock Elite Diary tasks", "difficulty" => "elite", "icon" => "13107"],
                ["task" => "Complete 3 Varrock Elite Diary tasks", "difficulty" => "elite", "icon" => "13107"],
                ["task" => "Complete 2 Western Provinces Elite Diary tasks", "difficulty" => "elite", "icon" => "13144"],
                ["task" => "Complete 2 Western Provinces Elite Diary tasks", "difficulty" => "elite", "icon" => "13144"],
                ["task" => "Complete 2 Wilderness Elite Diary tasks", "difficulty" => "elite", "icon" => "18649"],
                ["task" => "Complete 2 Wilderness Elite Diary tasks", "difficulty" => "elite", "icon" => "18649"],
                ["task" => "Complete 2 Wilderness Elite Diary tasks", "difficulty" => "elite", "icon" => "18649"],
            ]
        );
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('tasks');
    }
}
