<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateHardTreasureTrailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('hard_treasure_trails', function (Blueprint $table) {
            $table->id();
            $table->integer('account_id')->unsigned()->unique();
            $table->integer('kill_count')->default(0)->unsigned();
            $table->integer('rank')->default(0)->unsigned();
            $table->integer('obtained')->default(0)->unsigned();
            $table->integer('3rd_age_range_coif')->default(0)->unsigned();
            $table->integer('3rd_age_range_top')->default(0)->unsigned();
            $table->integer('3rd_age_range_legs')->default(0)->unsigned();
            $table->integer('3rd_age_vambraces')->default(0)->unsigned();
            $table->integer('3rd_age_robe_top')->default(0)->unsigned();
            $table->integer('3rd_age_robe')->default(0)->unsigned();
            $table->integer('3rd_age_mage_hat')->default(0)->unsigned();
            $table->integer('3rd_age_amulet')->default(0)->unsigned();
            $table->integer('3rd_age_plateskirt')->default(0)->unsigned();
            $table->integer('3rd_age_platelegs')->default(0)->unsigned();
            $table->integer('3rd_age_platebody')->default(0)->unsigned();
            $table->integer('3rd_age_full_helmet')->default(0)->unsigned();
            $table->integer('3rd_age_kiteshield')->default(0)->unsigned();
            $table->integer('gilded_platebody')->default(0)->unsigned();
            $table->integer('gilded_platelegs')->default(0)->unsigned();
            $table->integer('gilded_plateskirt')->default(0)->unsigned();
            $table->integer('gilded_full_helm')->default(0)->unsigned();
            $table->integer('gilded_kiteshield')->default(0)->unsigned();
            $table->integer('gilded_med_helm')->default(0)->unsigned();
            $table->integer('gilded_chainbody')->default(0)->unsigned();
            $table->integer('gilded_sq_shield')->default(0)->unsigned();
            $table->integer('gilded_2h_sword')->default(0)->unsigned();
            $table->integer('gilded_spear')->default(0)->unsigned();
            $table->integer('gilded_hasta')->default(0)->unsigned();
            $table->integer('robin_hood_hat')->default(0)->unsigned();
            $table->integer('dragon_boots_ornament_kit')->default(0)->unsigned();
            $table->integer('rune_defender_ornament_kit')->default(0)->unsigned();
            $table->integer('tzhaar-ket-om_ornament_kit')->default(0)->unsigned();
            $table->integer('berserker_necklace_ornament_kit')->default(0)->unsigned();
            $table->integer('rune_full_helm_(t)')->default(0)->unsigned();
            $table->integer('rune_platebody_(t)')->default(0)->unsigned();
            $table->integer('rune_platelegs_(t)')->default(0)->unsigned();
            $table->integer('rune_plateskirt_(t)')->default(0)->unsigned();
            $table->integer('rune_kiteshield_(t)')->default(0)->unsigned();
            $table->integer('rune_full_helm_(g)')->default(0)->unsigned();
            $table->integer('rune_platebody_(g)')->default(0)->unsigned();
            $table->integer('rune_platelegs_(g)')->default(0)->unsigned();
            $table->integer('rune_plateskirt_(g)')->default(0)->unsigned();
            $table->integer('rune_kiteshield_(g)')->default(0)->unsigned();
            $table->integer('zamorak_full_helm')->default(0)->unsigned();
            $table->integer('zamorak_platebody')->default(0)->unsigned();
            $table->integer('zamorak_platelegs')->default(0)->unsigned();
            $table->integer('zamorak_plateskirt')->default(0)->unsigned();
            $table->integer('zamorak_kiteshield')->default(0)->unsigned();
            $table->integer('guthix_full_helm')->default(0)->unsigned();
            $table->integer('guthix_platebody')->default(0)->unsigned();
            $table->integer('guthix_platelegs')->default(0)->unsigned();
            $table->integer('guthix_plateskirt')->default(0)->unsigned();
            $table->integer('guthix_kiteshield')->default(0)->unsigned();
            $table->integer('saradomin_full_helm')->default(0)->unsigned();
            $table->integer('saradomin_platebody')->default(0)->unsigned();
            $table->integer('saradomin_platelegs')->default(0)->unsigned();
            $table->integer('saradomin_plateskirt')->default(0)->unsigned();
            $table->integer('saradomin_kiteshield')->default(0)->unsigned();
            $table->integer('ancient_full_helm')->default(0)->unsigned();
            $table->integer('ancient_platebody')->default(0)->unsigned();
            $table->integer('ancient_platelegs')->default(0)->unsigned();
            $table->integer('ancient_plateskirt')->default(0)->unsigned();
            $table->integer('ancient_kiteshield')->default(0)->unsigned();
            $table->integer('armadyl_full_helm')->default(0)->unsigned();
            $table->integer('armadyl_platebody')->default(0)->unsigned();
            $table->integer('armadyl_platelegs')->default(0)->unsigned();
            $table->integer('armadyl_plateskirt')->default(0)->unsigned();
            $table->integer('armadyl_kiteshield')->default(0)->unsigned();
            $table->integer('bandos_full_helm')->default(0)->unsigned();
            $table->integer('bandos_platebody')->default(0)->unsigned();
            $table->integer('bandos_platelegs')->default(0)->unsigned();
            $table->integer('bandos_plateskirt')->default(0)->unsigned();
            $table->integer('bandos_kiteshield')->default(0)->unsigned();
            $table->integer('rune_shield_(h1)')->default(0)->unsigned();
            $table->integer('rune_shield_(h2)')->default(0)->unsigned();
            $table->integer('rune_shield_(h3)')->default(0)->unsigned();
            $table->integer('rune_shield_(h4)')->default(0)->unsigned();
            $table->integer('rune_shield_(h5)')->default(0)->unsigned();
            $table->integer('rune_helm_(h1)')->default(0)->unsigned();
            $table->integer('rune_helm_(h2)')->default(0)->unsigned();
            $table->integer('rune_helm_(h3)')->default(0)->unsigned();
            $table->integer('rune_helm_(h4)')->default(0)->unsigned();
            $table->integer('rune_helm_(h5)')->default(0)->unsigned();
            $table->integer('rune_platebody_(h1)')->default(0)->unsigned();
            $table->integer('rune_platebody_(h2)')->default(0)->unsigned();
            $table->integer('rune_platebody_(h3)')->default(0)->unsigned();
            $table->integer('rune_platebody_(h4)')->default(0)->unsigned();
            $table->integer('rune_platebody_(h5)')->default(0)->unsigned();
            $table->integer('saradomin_coif')->default(0)->unsigned();
            $table->integer('saradomin_dhide_body')->default(0)->unsigned();
            $table->integer('saradomin_chaps')->default(0)->unsigned();
            $table->integer('saradomin_bracers')->default(0)->unsigned();
            $table->integer('saradomin_dhide_boots')->default(0)->unsigned();
            $table->integer('saradomin_dhide_shield')->default(0)->unsigned();
            $table->integer('guthix_coif')->default(0)->unsigned();
            $table->integer('guthix_dhide_body')->default(0)->unsigned();
            $table->integer('guthix_chaps')->default(0)->unsigned();
            $table->integer('guthix_bracers')->default(0)->unsigned();
            $table->integer('guthix_dhide_boots')->default(0)->unsigned();
            $table->integer('guthix_dhide_shield')->default(0)->unsigned();
            $table->integer('zamorak_coif')->default(0)->unsigned();
            $table->integer('zamorak_dhide_body')->default(0)->unsigned();
            $table->integer('zamorak_chaps')->default(0)->unsigned();
            $table->integer('zamorak_bracers')->default(0)->unsigned();
            $table->integer('zamorak_dhide_boots')->default(0)->unsigned();
            $table->integer('zamorak_dhide_shield')->default(0)->unsigned();
            $table->integer('bandos_coif')->default(0)->unsigned();
            $table->integer('bandos_dhide_body')->default(0)->unsigned();
            $table->integer('bandos_chaps')->default(0)->unsigned();
            $table->integer('bandos_bracers')->default(0)->unsigned();
            $table->integer('bandos_dhide_boots')->default(0)->unsigned();
            $table->integer('bandos_dhide_shield')->default(0)->unsigned();
            $table->integer('armadyl_coif')->default(0)->unsigned();
            $table->integer('armadyl_dhide_body')->default(0)->unsigned();
            $table->integer('armadyl_chaps')->default(0)->unsigned();
            $table->integer('armadyl_bracers')->default(0)->unsigned();
            $table->integer('armadyl_dhide_boots')->default(0)->unsigned();
            $table->integer('armadyl_dhide_shield')->default(0)->unsigned();
            $table->integer('ancient_coif')->default(0)->unsigned();
            $table->integer('ancient_dhide_body')->default(0)->unsigned();
            $table->integer('ancient_chaps')->default(0)->unsigned();
            $table->integer('ancient_bracers')->default(0)->unsigned();
            $table->integer('ancient_dhide_boots')->default(0)->unsigned();
            $table->integer('ancient_dhide_shield')->default(0)->unsigned();
            $table->integer('red_dhide_body_(t)')->default(0)->unsigned();
            $table->integer('red_dhide_chaps_(t)')->default(0)->unsigned();
            $table->integer('red_dhide_body_(g)')->default(0)->unsigned();
            $table->integer('red_dhide_chaps_(g)')->default(0)->unsigned();
            $table->integer('blue_dhide_body_(t)')->default(0)->unsigned();
            $table->integer('blue_dhide_chaps_(t)')->default(0)->unsigned();
            $table->integer('blue_dhide_body_(g)')->default(0)->unsigned();
            $table->integer('blue_dhide_chaps_(g)')->default(0)->unsigned();
            $table->integer('enchanted_hat')->default(0)->unsigned();
            $table->integer('enchanted_top')->default(0)->unsigned();
            $table->integer('enchanted_robe')->default(0)->unsigned();
            $table->integer('saradomin_stole')->default(0)->unsigned();
            $table->integer('saradomin_crozier')->default(0)->unsigned();
            $table->integer('guthix_stole')->default(0)->unsigned();
            $table->integer('guthix_crozier')->default(0)->unsigned();
            $table->integer('zamorak_stole')->default(0)->unsigned();
            $table->integer('zamorak_crozier')->default(0)->unsigned();
            $table->integer('zombie_head')->default(0)->unsigned();
            $table->integer('cyclops_head')->default(0)->unsigned();
            $table->integer('pirates_hat')->default(0)->unsigned();
            $table->integer('red_cavalier')->default(0)->unsigned();
            $table->integer('white_cavalier')->default(0)->unsigned();
            $table->integer('navy_cavalier')->default(0)->unsigned();
            $table->integer('tan_cavalier')->default(0)->unsigned();
            $table->integer('dark_cavalier')->default(0)->unsigned();
            $table->integer('black_cavalier')->default(0)->unsigned();
            $table->integer('pith_helmet')->default(0)->unsigned();
            $table->integer('explorer_backpack')->default(0)->unsigned();
            $table->integer('thieving_bag')->default(0)->unsigned();
            $table->integer('green_dragon_mask')->default(0)->unsigned();
            $table->integer('blue_dragon_mask')->default(0)->unsigned();
            $table->integer('red_dragon_mask')->default(0)->unsigned();
            $table->integer('black_dragon_mask')->default(0)->unsigned();
            $table->integer('nunchaku')->default(0)->unsigned();
            $table->integer('dual_sai')->default(0)->unsigned();
            $table->integer('rune_cane')->default(0)->unsigned();
            $table->integer('amulet_of_glory_(t4)')->default(0)->unsigned();
            $table->integer('magic_comp_bow')->default(0)->unsigned();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('hard_treasure_trails');
    }
}
