<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateMediumTreasureTrailsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('medium_treasure_trails', function (Blueprint $table) {
            $table->id();
            $table->foreignId('account_id')->constrained();
            $table->integer('kill_count')->default(0)->unsigned();
            $table->integer('rank')->default(0)->unsigned();
            $table->integer('obtained')->default(0)->unsigned();
            $table->integer('ranger_boots')->default(0)->unsigned();
            $table->integer('wizard_boots')->default(0)->unsigned();
            $table->integer('holy_sandals')->default(0)->unsigned();
            $table->integer('climbing_boots_(g)')->default(0)->unsigned();
            $table->integer('spiked_manacles')->default(0)->unsigned();
            $table->integer('adamant_full_helm_(t)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(t)')->default(0)->unsigned();
            $table->integer('adamant_platelegs_(t)')->default(0)->unsigned();
            $table->integer('adamant_plateskirt_(t)')->default(0)->unsigned();
            $table->integer('adamant_kiteshield_(t)')->default(0)->unsigned();
            $table->integer('adamant_full_helm_(g)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(g)')->default(0)->unsigned();
            $table->integer('adamant_platelegs_(g)')->default(0)->unsigned();
            $table->integer('adamant_plateskirt_(g)')->default(0)->unsigned();
            $table->integer('adamant_kiteshield_(g)')->default(0)->unsigned();
            $table->integer('adamant_shield_(h1)')->default(0)->unsigned();
            $table->integer('adamant_shield_(h2)')->default(0)->unsigned();
            $table->integer('adamant_shield_(h3)')->default(0)->unsigned();
            $table->integer('adamant_shield_(h4)')->default(0)->unsigned();
            $table->integer('adamant_shield_(h5)')->default(0)->unsigned();
            $table->integer('adamant_helm_(h1)')->default(0)->unsigned();
            $table->integer('adamant_helm_(h2)')->default(0)->unsigned();
            $table->integer('adamant_helm_(h3)')->default(0)->unsigned();
            $table->integer('adamant_helm_(h4)')->default(0)->unsigned();
            $table->integer('adamant_helm_(h5)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(h1)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(h2)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(h3)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(h4)')->default(0)->unsigned();
            $table->integer('adamant_platebody_(h5)')->default(0)->unsigned();
            $table->integer('mithril_full_helm_(g)')->default(0)->unsigned();
            $table->integer('mithril_platebody_(g)')->default(0)->unsigned();
            $table->integer('mithril_platelegs_(g)')->default(0)->unsigned();
            $table->integer('mithril_plateskirt_(g)')->default(0)->unsigned();
            $table->integer('mithril_kiteshield_(g)')->default(0)->unsigned();
            $table->integer('mithril_full_helm_(t)')->default(0)->unsigned();
            $table->integer('mithril_platebody_(t)')->default(0)->unsigned();
            $table->integer('mithril_platelegs_(t)')->default(0)->unsigned();
            $table->integer('mithril_plateskirt_(t)')->default(0)->unsigned();
            $table->integer('mithril_kiteshield_(t)')->default(0)->unsigned();
            $table->integer('green_dhide_body_(g)')->default(0)->unsigned();
            $table->integer('green_dhide_body_(t)')->default(0)->unsigned();
            $table->integer('green_dhide_chaps_(g)')->default(0)->unsigned();
            $table->integer('green_dhide_chaps_(t)')->default(0)->unsigned();
            $table->integer('saradomin_mitre')->default(0)->unsigned();
            $table->integer('saradomin_cloak')->default(0)->unsigned();
            $table->integer('guthix_mitre')->default(0)->unsigned();
            $table->integer('guthix_cloak')->default(0)->unsigned();
            $table->integer('zamorak_mitre')->default(0)->unsigned();
            $table->integer('zamorak_cloak')->default(0)->unsigned();
            $table->integer('ancient_mitre')->default(0)->unsigned();
            $table->integer('ancient_cloak')->default(0)->unsigned();
            $table->integer('ancient_stole')->default(0)->unsigned();
            $table->integer('ancient_crozier')->default(0)->unsigned();
            $table->integer('armadyl_mitre')->default(0)->unsigned();
            $table->integer('armadyl_cloak')->default(0)->unsigned();
            $table->integer('armadyl_stole')->default(0)->unsigned();
            $table->integer('armadyl_crozier')->default(0)->unsigned();
            $table->integer('bandos_mitre')->default(0)->unsigned();
            $table->integer('bandos_cloak')->default(0)->unsigned();
            $table->integer('bandos_stole')->default(0)->unsigned();
            $table->integer('bandos_crozier')->default(0)->unsigned();
            $table->integer('red_boater')->default(0)->unsigned();
            $table->integer('green_boater')->default(0)->unsigned();
            $table->integer('orange_boater')->default(0)->unsigned();
            $table->integer('black_boater')->default(0)->unsigned();
            $table->integer('blue_boater')->default(0)->unsigned();
            $table->integer('pink_boater')->default(0)->unsigned();
            $table->integer('purple_boater')->default(0)->unsigned();
            $table->integer('white_boater')->default(0)->unsigned();
            $table->integer('red_headband')->default(0)->unsigned();
            $table->integer('black_headband')->default(0)->unsigned();
            $table->integer('brown_headband')->default(0)->unsigned();
            $table->integer('white_headband')->default(0)->unsigned();
            $table->integer('blue_headband')->default(0)->unsigned();
            $table->integer('gold_headband')->default(0)->unsigned();
            $table->integer('pink_headband')->default(0)->unsigned();
            $table->integer('green_headband')->default(0)->unsigned();
            $table->integer('crier_hat')->default(0)->unsigned();
            $table->integer('crier_coat')->default(0)->unsigned();
            $table->integer('crier_bell')->default(0)->unsigned();
            $table->integer('adamant_cane')->default(0)->unsigned();
            $table->integer('arceuus_banner')->default(0)->unsigned();
            $table->integer('piscarilius_banner')->default(0)->unsigned();
            $table->integer('hosidius_banner')->default(0)->unsigned();
            $table->integer('shayzien_banner')->default(0)->unsigned();
            $table->integer('lovakengj_banner')->default(0)->unsigned();
            $table->integer('cabbage_round_shield')->default(0)->unsigned();
            $table->integer('black_unicorn_mask')->default(0)->unsigned();
            $table->integer('white_unicorn_mask')->default(0)->unsigned();
            $table->integer('cat_mask')->default(0)->unsigned();
            $table->integer('penguin_mask')->default(0)->unsigned();
            $table->integer('leprechaun_hat')->default(0)->unsigned();
            $table->integer('black_leprechaun_hat')->default(0)->unsigned();
            $table->integer('wolf_mask')->default(0)->unsigned();
            $table->integer('wolf_cloak')->default(0)->unsigned();
            $table->integer('purple_elegant_shirt')->default(0)->unsigned();
            $table->integer('purple_elegant_blouse')->default(0)->unsigned();
            $table->integer('purple_elegant_legs')->default(0)->unsigned();
            $table->integer('purple_elegant_skirt')->default(0)->unsigned();
            $table->integer('black_elegant_shirt')->default(0)->unsigned();
            $table->integer('white_elegant_blouse')->default(0)->unsigned();
            $table->integer('black_elegant_legs')->default(0)->unsigned();
            $table->integer('white_elegant_skirt')->default(0)->unsigned();
            $table->integer('pink_elegant_shirt')->default(0)->unsigned();
            $table->integer('pink_elegant_blouse')->default(0)->unsigned();
            $table->integer('pink_elegant_legs')->default(0)->unsigned();
            $table->integer('pink_elegant_skirt')->default(0)->unsigned();
            $table->integer('gold_elegant_shirt')->default(0)->unsigned();
            $table->integer('gold_elegant_blouse')->default(0)->unsigned();
            $table->integer('gold_elegant_legs')->default(0)->unsigned();
            $table->integer('gold_elegant_skirt')->default(0)->unsigned();
            $table->integer('gnomish_firelighter')->default(0)->unsigned();
            $table->integer('strength_amulet_(t)')->default(0)->unsigned();
            $table->integer('yew_comp_bow')->default(0)->unsigned();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('medium_treasure_trails');
    }
}
