<?php

use App\Models\Account;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * SPEC §8 Live Feed — append-only event log generated by the push pipeline.
     */
    public function up(): void
    {
        Schema::create('feed_events', function (Blueprint $table) {
            $table->id();
            $table->foreignIdFor(Account::class)->constrained()->cascadeOnDelete();
            $table->string('type');
            $table->jsonb('payload');
            $table->timestamp('occurred_at')->index();
            $table->timestamps();

            // Reverse-chronological queries are the only read path.
            $table->index(['occurred_at', 'id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('feed_events');
    }
};
