<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Data Freshness
    |--------------------------------------------------------------------------
    |
    | Per SPEC §5.3, each data type on a player profile carries a "last updated"
    | timestamp. Once the data is older than the configured threshold (minutes),
    | the UI flags it as stale.
    |
    | Stays a config value for now; will migrate to instance Settings (§12)
    | once the admin backend lands.
    |
    */

    'freshness' => [
        'stale_after_minutes' => (int) env('FRESHNESS_STALE_AFTER_MINUTES', 60),
    ],

    /*
    |--------------------------------------------------------------------------
    | Live Feed (SPEC §8)
    |--------------------------------------------------------------------------
    |
    | Generated by the push pipeline. Thresholds keep the feed signal-heavy —
    | the level-up filter avoids spamming every +1, the loot floor avoids
    | broadcasting trivial drops.
    |
    */

    'feed' => [

        // Notable level thresholds — emit a LEVEL_UP event only when a skill
        // *crosses* one of these (passing 70 emits one event, 71-79 stay quiet).
        'level_up_thresholds' => [50, 60, 70, 80, 85, 90, 95, 99],

        // Drops below this GP value (plugin-computed) don't make the feed.
        // Plugin pushes total_value; 0 / missing falls through the filter.
        'loot_min_value' => (int) env('FEED_LOOT_MIN_VALUE', 100_000),

        // Number of events rendered on /feed.
        'page_size' => (int) env('FEED_PAGE_SIZE', 50),

        // Client poll interval (ms). usePoll() reloads only the events prop.
        'poll_interval_ms' => (int) env('FEED_POLL_INTERVAL_MS', 15_000),

    ],

];
