<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Data Freshness
    |--------------------------------------------------------------------------
    |
    | Per SPEC §5.3, each data type on a player profile carries a "last updated"
    | timestamp. Once the data is older than the configured threshold (minutes),
    | the UI flags it as stale.
    |
    | Stays a config value for now; will migrate to instance Settings (§12)
    | once the admin backend lands.
    |
    */

    'freshness' => [
        'stale_after_minutes' => (int) env('FRESHNESS_STALE_AFTER_MINUTES', 60),
    ],

    /*
    |--------------------------------------------------------------------------
    | Presence
    |--------------------------------------------------------------------------
    |
    | An account is "online" while its last plugin heartbeat (accounts.last_seen_at)
    | is within this window. The plugin pings roughly once a minute, so a few
    | minutes of grace covers a missed beat without showing stale presence.
    |
    */

    'presence' => [
        'online_within_minutes' => (int) env('PRESENCE_ONLINE_WITHIN_MINUTES', 3),
    ],

    /*
    |--------------------------------------------------------------------------
    | Live Map
    |--------------------------------------------------------------------------
    |
    | An account appears on the Live Map while its last position push
    | (accounts.position_updated_at) is within this window. The plugin pushes
    | frequently while sharing is enabled, so a short window keeps the map
    | current and drops players quickly once they stop sharing or log out.
    |
    */

    'map' => [
        'visible_within_minutes' => (int) env('MAP_VISIBLE_WITHIN_MINUTES', 2),
    ],

    /*
    |--------------------------------------------------------------------------
    | Resource Packs (SPEC §6)
    |--------------------------------------------------------------------------
    |
    | How many community-hub packs a single member may install. The owner/admin
    | is exempt (instance-managed packs don't count against anyone) and the
    | bundled Default Vanilla is never counted. Deleting a pack frees a slot.
    |
    */

    'resource_packs' => [
        'user_install_limit' => (int) env('RESOURCE_PACK_USER_INSTALL_LIMIT', 5),
    ],

    /*
    |--------------------------------------------------------------------------
    | Live Feed (SPEC §8)
    |--------------------------------------------------------------------------
    |
    | Generated by the push pipeline. Thresholds keep the feed signal-heavy —
    | the level-up filter avoids spamming every +1, the loot floor avoids
    | broadcasting trivial drops.
    |
    */

    'feed' => [

        // Notable level thresholds — emit a LEVEL_UP event only when a skill
        // *crosses* one of these (passing 70 emits one event, 71-79 stay quiet).
        'level_up_thresholds' => [50, 60, 70, 80, 85, 90, 95, 99],

        // Drops below this GP value (plugin-computed) don't make the feed.
        // Plugin pushes total_value; 0 / missing falls through the filter.
        'loot_min_value' => (int) env('FEED_LOOT_MIN_VALUE', 100_000),

        // Number of events rendered on /feed.
        'page_size' => (int) env('FEED_PAGE_SIZE', 50),

        // Client poll interval (ms). usePoll() reloads only the events prop.
        'poll_interval_ms' => (int) env('FEED_POLL_INTERVAL_MS', 15_000),

    ],

];
